version: '3.8'

#services:
#  sqlserver:
#   image: mcr.microsoft.com/mssql/server:2022-latest
#   container_name: sqlserver
#   ports:
#     - "1433:1433" # Map container port 1433 to host port 1433
#   environment:
#     ACCEPT_EULA: "Y" # Accept the End User License Agreement
#     SA_PASSWORD: "YourStrong!Passw0rd" # Set the SQL Server system administrator (SA) password
#   volumes:
#     - sqlserver_data:/var/opt/mssql # Persistent data storage

#volumes:
# sqlserver_data:
services:
  db:
    image: postgres:alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres_data:
    driver: local

networks:
  mynetwork:
    driver: bridge